# Generated by Django 3.2.16 on 2023-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl',
            name='codeCom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bl',
            name='codebl',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='codecom',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='codebl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='codefac',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lignebl',
            name='codebl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lignecom',
            name='codeCom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lignefac',
            name='codefac',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lignereglement',
            name='codereg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reglement',
            name='codefac',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reglement',
            name='codereg',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
