# Generated by Django 3.2.16 on 2023-08-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0005_auto_20230823_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecomdraft',
            options={'verbose_name': 'Ligne Panier', 'verbose_name_plural': 'Lignes Panier'},
        ),
        migrations.AddField(
            model_name='tes1',
            name='champ2',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='facture',
            name='bl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djafa.bl'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='bl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djafa.bl'),
        ),
    ]
