# Generated by Django 3.2.16 on 2023-08-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bl',
            fields=[
                ('idlignebl', models.AutoField(primary_key=True, serialize=False)),
                ('dateliv', models.DateField()),
                ('totalht', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalttc', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalpaye', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('commentaire', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'BL',
                'verbose_name_plural': 'BL',
            },
        ),
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('idcat', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('admail', models.EmailField(max_length=50)),
                ('localisation', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('idcom', models.AutoField(primary_key=True, serialize=False)),
                ('datecom', models.DateField()),
                ('totalht', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalttc', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalpaye', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('nbreligne', models.IntegerField(default=0)),
                ('commentaire', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('idfac', models.AutoField(primary_key=True, serialize=False)),
                ('datefact', models.DateField()),
                ('totalht', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalttc', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalpaye', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('commentaire', models.CharField(max_length=500)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.bl')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.client')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='fournisseur',
            fields=[
                ('idfour', models.AutoField(primary_key=True, serialize=False)),
                ('nomfour', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('admail', models.EmailField(max_length=50)),
                ('localisation', models.CharField(max_length=300)),
                ('photoid', models.ImageField(default=0, upload_to='')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='modepaie',
            fields=[
                ('idmode', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mode Reglement',
                'verbose_name_plural': 'Modes Reglement',
            },
        ),
        migrations.CreateModel(
            name='statut',
            fields=[
                ('idstatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
            },
        ),
        migrations.CreateModel(
            name='tes1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reglement',
            fields=[
                ('idregl', models.AutoField(primary_key=True, serialize=False)),
                ('totalfacture', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalreglement', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('commentaire', models.CharField(max_length=500)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.bl')),
                ('idcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.client')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.statut')),
            ],
            options={
                'verbose_name': 'Reglement',
                'verbose_name_plural': 'Reglements',
            },
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('idpro', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('qte', models.IntegerField(default=0)),
                ('imageprod', models.ImageField(upload_to='')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='lignereglement',
            fields=[
                ('idlignereg', models.AutoField(primary_key=True, serialize=False)),
                ('datereg', models.DateField()),
                ('montantregle', models.IntegerField(default=0)),
                ('commentaire', models.CharField(max_length=500)),
                ('idmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.modepaie')),
                ('idreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.reglement')),
            ],
            options={
                'verbose_name': 'Ligne Reglement',
                'verbose_name_plural': 'Lignes Reglement',
            },
        ),
        migrations.CreateModel(
            name='Lignefac',
            fields=[
                ('idlignefac', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default=0)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('prixtotal', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idfac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.facture')),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.produit')),
            ],
            options={
                'verbose_name': 'Ligne Facture',
                'verbose_name_plural': 'Lignes Factures',
            },
        ),
        migrations.CreateModel(
            name='lignecom',
            fields=[
                ('idlcom', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default=0)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('prixtotal', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.produit')),
            ],
            options={
                'verbose_name': 'Ligne Commande',
                'verbose_name_plural': 'Lignes Commande',
            },
        ),
        migrations.CreateModel(
            name='lignebl',
            fields=[
                ('idlcom', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField(default=0)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('prixtotal', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.bl')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.produit')),
            ],
            options={
                'verbose_name': 'Ligne BL',
                'verbose_name_plural': 'Lignes BL',
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='idstatut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.statut'),
        ),
        migrations.AddField(
            model_name='commande',
            name='idstatut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.statut'),
        ),
        migrations.AddField(
            model_name='bl',
            name='idcli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.client'),
        ),
        migrations.AddField(
            model_name='bl',
            name='idcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande'),
        ),
        migrations.AddField(
            model_name='bl',
            name='idstatut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.statut'),
        ),
    ]
