# Generated by Django 3.2.16 on 2023-08-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0007_alter_lignebl_idlignebl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lignebl',
        ),
    ]
