# Generated by Django 3.2.16 on 2023-08-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0008_delete_lignebl'),
    ]

    operations = [
        migrations.CreateModel(
            name='lignebl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('prixtotal', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.bl')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idlcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.lignecom')),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.produit')),
            ],
            options={
                'verbose_name': 'Ligne BL',
                'verbose_name_plural': 'Lignes BL',
            },
        ),
    ]
