# Generated by Django 3.2.16 on 2023-08-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0009_lignebl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecomdraft',
            options={'verbose_name': 'Ligne Panier', 'verbose_name_plural': 'Lignes Panier'},
        ),
        migrations.RemoveField(
            model_name='lignebl',
            name='idlcom',
        ),
    ]
