# Generated by Django 3.2.16 on 2023-08-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0010_auto_20230825_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bl',
            old_name='idbl',
            new_name='idlignebl',
        ),
        migrations.AddField(
            model_name='lignebl',
            name='idlcom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djafa.lignecom'),
        ),
        migrations.AlterField(
            model_name='bl',
            name='idcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande'),
        ),
    ]
