# Generated by Django 3.2.16 on 2023-08-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djafa', '0012_auto_20230825_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='bl',
            fields=[
                ('idlignebl', models.AutoField(primary_key=True, serialize=False)),
                ('dateliv', models.DateField()),
                ('totalht', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalttc', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('totalpaye', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('commentaire', models.CharField(max_length=500)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idstatut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.statut')),
            ],
            options={
                'verbose_name': 'BL',
                'verbose_name_plural': 'BL',
            },
        ),
        migrations.AddField(
            model_name='tes1',
            name='champ2',
            field=models.TextField(default=0),
        ),
        migrations.CreateModel(
            name='lignebl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField(default=0)),
                ('prixu', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('prixtotal', models.DecimalField(decimal_places=2, default=0, max_digits=100000)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.bl')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.commande')),
                ('idlcom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djafa.lignecom')),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djafa.produit')),
            ],
            options={
                'verbose_name': 'Ligne BL',
                'verbose_name_plural': 'Lignes BL',
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='bl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djafa.bl'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='bl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djafa.bl'),
        ),
    ]
