# Generated by Django 3.2.16 on 2023-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djafa', '0013_auto_20230825_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignebl',
            name='id',
        ),
        migrations.AlterField(
            model_name='lignebl',
            name='idlcom',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
